create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
create table category (id bigint generated by default as identity, name varchar(255), primary key (id))
create table todo (id bigint generated by default as identity, description varchar(255), name varchar(255), status varchar(255), timestamp timestamp, category_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, birthdate date, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile_num varchar(255), primary key (id))
alter table todo add constraint FKeh6uro943emclp6kr1d4wysmo foreign key (category_id) references category
alter table todo add constraint FK2ft3dfk1d3uw77pas3xqwymm7 foreign key (user_id) references user
